export const MAX_CHILDREN = "10";
export const MAX_ADULTS = "10";
export const MIN_ADULTS = "1";
export const MIN_CHILDREN = "0";
export const BASE_URL = "https://sky-scrapper.p.rapidapi.com/api";
export const POPULAR_LOCATIONS = [
  "New York",
  "London",
  "Paris",
  "Tokyo",
  "Los Angeles",
  "Dubai",
  "Singapore",
  "Hong Kong",
  "Sydney",
  "Rome",
  "Istanbul",
  "Bangkok",
  "Toronto",
  "Madrid",
  "Amsterdam",
  "Berlin",
  "San Francisco",
  "Chicago",
  "Miami",
  "Barcelona",
  "Vienna",
  "Seoul",
  "Shanghai",
  "Beijing",
  "Mumbai",
  "São Paulo",
  "Buenos Aires",
  "Mexico City",
  "Kuala Lumpur",
  "Zurich",
  "Frankfurt",
  "Delhi",
  "Jakarta",
  "Cairo",
  "Lisbon",
  "Munich",
  "Copenhagen",
  "Prague",
  "Brussels",
  "Moscow",
  "Doha",
  "Riyadh",
  "Johannesburg",
  "Manila",
  "Hanoi",
  "Athens",
  "Stockholm",
  "Oslo",
  "Helsinki",
  "Dublin",
  "Montreal",
  "Vancouver",
  "Washington D.C.",
  "Houston",
  "Dallas",
  "Atlanta",
  "Seattle",
  "Boston",
  "Melbourne",
  "Auckland",
  "Cape Town",
  "Bogota",
  "Lima",
  "Warsaw",
  "Budapest",
  "Rio de Janeiro",
  "Santiago",
  "Taipei",
  "Shenzhen",
  "Bangalore",
  "Chennai",
  "Ho Chi Minh City",
  "Tel Aviv",
  "Marrakech",
  "Bali",
  "Phuket",
  "Edinburgh",
  "Reykjavik",
  "Kiev",
  "Havana",
  "San Diego",
  "San Jose",
  "Nairobi",
  "Casablanca",
  "Muscat",
  "Christchurch",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Montevideo",
  "Luxembourg",
  "Valencia",
  "Seville",
  "Florence",
  "Nice",
  "Lyon",
  "Marseille",
  "Cologne",
  "Düsseldorf",
  "Hamburg",
  "Geneva",
  "Basel",
  "Lagos",
  "Accra",
  "Addis Ababa",
  "Dar es Salaam",
  "Algiers",
  "Tunis",
  "Kuwait City",
  "Amman",
  "Beirut",
  "Tbilisi",
  "Yerevan",
  "Baku",
  "Ulaanbaatar",
  "Kathmandu",
  "Malé",
  "Colombo",
  "Dhaka",
  "Karachi",
  "Lahore",
  "Islamabad",
];
